# Generated by Django 4.2.1 on 2024-11-24 17:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Interview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('interviewer', models.CharField(max_length=255)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the program', max_length=255, unique=True)),
                ('level', models.CharField(choices=[('Bachelors', 'Bachelors'), ('Masters', 'Masters'), ('PhD', 'PhD'), ('Diploma', 'Diploma')], help_text='Level of the program', max_length=50)),
                ('min_fee', models.DecimalField(decimal_places=2, help_text='Minimum fee for the program', max_digits=10)),
                ('scholarship', models.BooleanField(default=False, help_text='Is scholarship available?')),
                ('scholarship_details', models.TextField(blank=True, help_text='Details about scholarship, if applicable', null=True)),
                ('qualification_required', models.TextField(help_text='Minimum qualifications required for the program')),
                ('location', models.CharField(help_text='Location of the program', max_length=255)),
                ('time_span', models.DurationField(help_text='Duration of the program (e.g., 2 years, 6 months)')),
                ('total_fee', models.DecimalField(decimal_places=2, help_text='Total fee for the program', max_digits=15)),
                ('is_active', models.BooleanField(default=True, help_text='Is the program currently active?')),
                ('currently_in_program', models.IntegerField(default=0, help_text='Number of students currently in the program')),
                ('visa_requirements', models.TextField(blank=True, help_text='Visa requirements for the program', null=True)),
                ('pros_and_cons', models.TextField(blank=True, help_text='Pros and cons of the program', null=True)),
                ('one_line_description', models.CharField(blank=True, help_text='One-line description of the program', max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Program',
                'verbose_name_plural': 'Programs',
                'ordering': ['level', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('date_of_birth', models.DateField()),
                ('education_qualification', models.TextField(help_text='Details of education qualification')),
                ('subjects_studied', models.TextField(help_text='Subjects studied')),
                ('countries_looking_to_study', models.TextField(help_text='Countries looking to study')),
                ('program_looking_for', models.CharField(help_text='Program looking for', max_length=255)),
                ('address', models.TextField(help_text='Home address')),
                ('phone_number', models.CharField(help_text='Phone number', max_length=15)),
                ('nationality', models.CharField(help_text='Nationality', max_length=100)),
                ('passport_number', models.CharField(help_text='Passport number', max_length=50, unique=True)),
                ('previous_institutions', models.TextField(help_text='Previous institutions attended')),
                ('extracurricular_activities', models.TextField(blank=True, help_text='Extracurricular activities', null=True)),
                ('personal_statement', models.TextField(blank=True, help_text='Personal statement', null=True)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='app.program')),
            ],
        ),
        migrations.CreateModel(
            name='WorkExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(help_text='Name of the company', max_length=255)),
                ('position', models.CharField(help_text='Position held', max_length=255)),
                ('start_date', models.DateField(help_text='Start date of the work experience')),
                ('end_date', models.DateField(blank=True, help_text='End date of the work experience', null=True)),
                ('responsibilities', models.TextField(help_text='Responsibilities and achievements')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_experiences', to='app.student')),
            ],
        ),
        migrations.CreateModel(
            name='MeetingLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('interview', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='meeting_link', to='app.interview')),
            ],
        ),
        migrations.CreateModel(
            name='LanguageTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('English', 'English'), ('German', 'German'), ('Spanish', 'Spanish'), ('French', 'French'), ('Russian', 'Russian')], help_text='Language of the test', max_length=50)),
                ('test_name', models.CharField(choices=[('SAT', 'SAT'), ('IELTS', 'IELTS'), ('TOEFL', 'TOEFL'), ('DUOLINGO', 'DUOLINGO'), ('PTE', 'PTE')], help_text='Name of the language test', max_length=50)),
                ('level', models.CharField(choices=[('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('Advanced', 'Advanced'), ('Proficient', 'Proficient')], help_text='Level of proficiency', max_length=50)),
                ('score', models.DecimalField(decimal_places=2, help_text='Score obtained in the test', max_digits=5)),
                ('test_date', models.DateField(help_text='Date of the test')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='language_tests', to='app.student')),
            ],
        ),
        migrations.AddField(
            model_name='interview',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interviews', to='app.student'),
        ),
    ]
